// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _4I4U_LiteTrak.Model;

#nullable disable

namespace _4I4ULiteTrak.Migrations
{
    [DbContext(typeof(FeuDbContext))]
    partial class FeuDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("_4I4U_LiteTrak.Model.Feu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DoitClignoter")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FeuId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InfoTraffic")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TempsAjout")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FeuId");

                    b.ToTable("Feus");
                });

            modelBuilder.Entity("_4I4U_LiteTrak.Model.Feu", b =>
                {
                    b.HasOne("_4I4U_LiteTrak.Model.Feu", null)
                        .WithMany("FeuxAval")
                        .HasForeignKey("FeuId");
                });

            modelBuilder.Entity("_4I4U_LiteTrak.Model.Feu", b =>
                {
                    b.Navigation("FeuxAval");
                });
#pragma warning restore 612, 618
        }
    }
}
